### ISSUE TITLE
请问ppt和图片要如何查看？

### ISSUE THREAD

**Issue by Smileteeth7** [OrangeX4/NJUAI-Notes#3]
是要通过安装什么东西来查看吗？
感谢大佬:pray::pray:

**Comment by OrangeX4** [comment]
抱歉，之前出现 bug 了，现在修好了，现在不管是在 github 直接看，还是在笔记网页 notes.orangex4.cool 中打开都行。

**Comment by Smileteeth7** [comment]
哇:smiley:感谢感谢
