### ISSUE TITLE
你好，我想问一下知识表示那个课有录屏吗？

### ISSUE THREAD

**Issue by hexiao5886** [OrangeX4/NJUAI-Notes#7]

**Comment by hexiao5886** [comment]
我的意思是，老师上课的视频。看了zyz老师关于《关于KRP课程的内容梳理》深受吸引，如果可以希望能够听一下老师讲课

**Comment by OrangeX4** [comment]
KR 课程只有一部分录屏，你需要的话倒是也可以发给你。

可以提供一个邮箱吗？我私下发我整理的视频给你。

**Comment by hexiao5886** [comment]
好的好的，非常感谢。我的邮箱：1309028818@qq.com
